version: "3.8"
services:
  challenge1:
    build:
      context: ./challenge1/
      dockerfile: Dockerfile
    container_name: challenge1
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=aiq
      - DATABASE_PASSWORD=aiq
      - DATABASE_NAME=aiq-db
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  challenge2:
    container_name: challenge2
    build:
      context: ./challenge2/
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - DB_URL=postgresql://aiq:aiq@db:5432/aiq-db
    depends_on:
      - db
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: aiq
      POSTGRES_PASSWORD: aiq
      POSTGRES_DB: aiq-db
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: usman@aiq.com
      PGADMIN_DEFAULT_PASSWORD: aiq
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data: